import type {
  BlockProps,
  PostComponent,
  PostComponentType,
} from "./schema";

export interface PostComponentDefinition {
  label: string;
  description: string;
}

export const postComponentRegistry = {
  prose: {
    label: "Text",
    description: "Write and format the body of your post with Markdown.",
  },
  githubDiscussions: {
    label: "GitHub Discussions",
    description: "Add Giscus-powered comments and reactions backed by a GitHub repository.",
  },
} satisfies Record<PostComponentType, PostComponentDefinition>;

export interface GitHubDiscussionsConfigIssue {
  field: keyof BlockProps<"githubDiscussions">;
  message: string;
}

const REPO_PATTERN = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/;
const NODE_ID_PATTERN = /^[A-Za-z0-9_=-]{8,}$/;

/** Return actionable setup issues without preventing an author from saving an unfinished component. */
export function getGitHubDiscussionsConfigIssues(
  props: BlockProps<"githubDiscussions">,
): GitHubDiscussionsConfigIssue[] {
  const issues: GitHubDiscussionsConfigIssue[] = [];

  if (!props.repo.trim()) {
    issues.push({ field: "repo", message: "Choose the public repository that will store discussions." });
  } else if (!REPO_PATTERN.test(props.repo.trim())) {
    issues.push({ field: "repo", message: "Use the owner/repository format." });
  }

  if (!props.repoId.trim()) {
    issues.push({ field: "repoId", message: "Add the repository ID generated by giscus.app." });
  } else if (!NODE_ID_PATTERN.test(props.repoId.trim())) {
    issues.push({ field: "repoId", message: "Use the repository node ID generated by Giscus." });
  }

  if (!props.category.trim()) {
    issues.push({ field: "category", message: "Choose a GitHub Discussions category." });
  }

  if (!props.categoryId.trim()) {
    issues.push({ field: "categoryId", message: "Add the category ID generated by giscus.app." });
  } else if (!NODE_ID_PATTERN.test(props.categoryId.trim())) {
    issues.push({ field: "categoryId", message: "Use the category node ID generated by Giscus." });
  }

  if (props.mapping === "specific" && !props.term?.trim()) {
    issues.push({ field: "term", message: "Add the stable term used to find this post's discussion." });
  }

  if (props.mapping === "number" && !props.discussionNumber) {
    issues.push({ field: "discussionNumber", message: "Add the GitHub discussion number for this post." });
  }

  return issues;
}

export function isGitHubDiscussionsConfigured(
  props: BlockProps<"githubDiscussions">,
): boolean {
  return getGitHubDiscussionsConfigIssues(props).length === 0;
}

export function createPostComponent(
  type: "prose",
  options?: { id?: string; repo?: string },
): Extract<PostComponent, { type: "prose" }>;
export function createPostComponent(
  type: "githubDiscussions",
  options?: {
    id?: string;
    repo?: string;
    repoId?: string;
    category?: string;
    categoryId?: string;
  },
): Extract<PostComponent, { type: "githubDiscussions" }>;
export function createPostComponent(
  type: PostComponentType,
  options: {
    id?: string;
    repo?: string;
    repoId?: string;
    category?: string;
    categoryId?: string;
  } = {},
): PostComponent {
  const id = options.id ?? `${type}-${Date.now().toString(36)}`;
  if (type === "prose") {
    return {
      type,
      id,
      props: { markdown: "", html: "" },
    };
  }
  return {
    type,
    id,
    props: {
      repo: options.repo ?? "",
      repoId: options.repoId ?? "",
      category: options.category ?? "",
      categoryId: options.categoryId ?? "",
      mapping: "pathname",
      strict: true,
      reactionsEnabled: true,
      inputPosition: "top",
      theme: "preferred_color_scheme",
      lang: "en",
    },
  };
}

export function movePostComponent(
  components: readonly PostComponent[],
  id: string,
  toIndex: number,
): PostComponent[] {
  const fromIndex = components.findIndex((component) => component.id === id);
  if (fromIndex < 0 || toIndex < 0 || toIndex >= components.length || fromIndex === toIndex) {
    return [...components];
  }
  const next = [...components];
  const [component] = next.splice(fromIndex, 1);
  next.splice(toIndex, 0, component!);
  return next;
}

export function removePostComponent(
  components: readonly PostComponent[],
  id: string,
): PostComponent[] {
  return components.filter((component) => component.id !== id);
}

export function updatePostComponent<T extends PostComponentType>(
  components: readonly PostComponent[],
  id: string,
  props: Partial<BlockProps<T>>,
): PostComponent[] {
  return components.map((component) =>
    component.id === id
      ? ({ ...component, props: { ...component.props, ...props } } as PostComponent)
      : component,
  );
}

/** Migrate a locally-saved draft from the previous single-Markdown composer into the component list. */
export function applyLegacyMarkdownDraft(
  components: readonly PostComponent[],
  markdown: string,
  fallbackId = "prose-migrated-draft",
): PostComponent[] {
  const existingText = components.find((component) => component.type === "prose");
  if (existingText) {
    return updatePostComponent<"prose">(components, existingText.id, { markdown, html: "" });
  }
  return [
    {
      ...createPostComponent("prose", { id: fallbackId }),
      props: { markdown, html: "" },
    },
    ...components,
  ];
}
